server:
  port: 10083

spring:
  datasource:
    url: jdbc:mysql://10.100.216.143:3500/starfish_identity?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
    username: starfish
    password: starfish123456
